name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      dbpath: ${{secrets.DBURL}}
      privatekey: ${{secrets.KEY}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: git checkout test/backend
      - run: echo 'db="$dbpath"' >> ./Backend/.env
      - run: echo 'secret_key="$privatekey"' >> ./Backend/.env
      - run: bash ./Scripts/test_backend.sh